name: release

on:
  push:
    branches: ['master']
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.dockerignore'
  workflow_dispatch:
env:
  RUST_VERSION: 1.95.0
jobs:
  linux: 
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/inkroomtemp/rust_musl_build:1.95.0
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          apt update
          apt install -y nasm curl pkg-config ca-certificates ffmpeg bsdmainutils unzip libavcodec-dev libavformat-dev libavutil-dev libavfilter-dev libavdevice-dev
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - name: Build
        run: |
          cargo build --release --target=$(arch)-unknown-linux-musl && mv target/x86_64-unknown-linux-musl/release/m3u8-dl target/x86_64-unknown-linux-musl/release/m3u8-dl-wioutffmpeg
          cargo build --release --target=$(arch)-unknown-linux-musl --features build
          rm -rf target/x86_64-unknown-linux-musl/release/m3u8-dl.d
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: app-linux
          path: target/x86_64-unknown-linux-musl/release/m3u8-dl*
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install dependencies
        env:
          FFMPEG_DOWNLOAD_URL: https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z
        run: |
          $VCINSTALLDIR = $(& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath)
          Add-Content $env:GITHUB_ENV "LIBCLANG_PATH=${VCINSTALLDIR}\VC\Tools\LLVM\x64\bin`n"
          Invoke-WebRequest "${env:FFMPEG_DOWNLOAD_URL}" -OutFile ffmpeg-release-full-shared.7z
          7z x ffmpeg-release-full-shared.7z
          mkdir ffmpeg
          mv ffmpeg-*/* ffmpeg/
          Add-Content $env:GITHUB_ENV "FFMPEG_DIR=${pwd}\ffmpeg`n"
          Add-Content $env:GITHUB_PATH "${pwd}\ffmpeg\bin`n"
      - name: Install dependencies
        run: |
          vcpkg install ffmpeg:x64-windows-static
          ls C:/vcpkg/packages/ffmpeg_x64-windows-static/
          ls C:/vcpkg/packages/ffmpeg_x64-windows-static/lib
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - name: Build
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
          FFMPEG_DIR: "C:/vcpkg/packages/ffmpeg_x64-windows-static"
        run: |
          cargo build --release --features static -vv
      - name: Check linked DLLs
        shell: pwsh
        run: |
          Select-String -Path "target\release\m3u8-dl.exe" -Pattern '\.dll\b' -AllMatches | 
          ForEach-Object { $_.Matches.Value } | 
          Sort-Object -Unique
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: app-windows
          path: target/release/m3u8-dl.exe
  windows-check:
    needs: ["windows"]
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          pattern: app-*
          path: app/
      - name: Check
        run: |
          ./app/m3u8-dl.exe --help
  mac: 
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          brew install ffmpeg pkg-config
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - name: Build
        run: |
          cargo build --release --features build && mv target/release/m3u8-dl target/release/m3u8-dl-mac
          cargo build --release --features build && mv target/release/m3u8-dl target/release/m3u8-dl-mac-withoutffmpeg
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: app-mac
          path: target/release/m3u8-dl-mac*
  release:
    runs-on: ubuntu-24.04
    needs: ["mac","linux","windows-check"]
    permissions:
        contents: write
        packages: write
    steps:
        - name: Checkout repository
          uses: actions/checkout@v6
          with:
            fetch-tags: true
            fetch-depth: 0
        - name: Download artifacts
          uses: actions/download-artifact@v8
          with:
            merge-multiple: true
            pattern: app-*
            path: app/
        - name: Release Ready
          id: ready
          env:
            GH_TOKEN: ${{ github.token }}
          run: |
            new_tag=$(date +%Y%m%d)
            now_tag=$(curl -sSf https://api.github.com/repos/inkroom/m3u8-dl/releases/latest | jq --raw-output '.tag_name')
            if [[ "$new_tag" = "$now_tag" ]]; then
              echo "delete $now_tag"
              gh release delete $now_tag
              now_tag=$(curl -sSf https://api.github.com/repos/inkroom/m3u8-dl/releases | jq --raw-output '.[0].tag_name')
            fi
            commit=$(git rev-list -n 1 $now_tag)
            echo "$commit"

            temp=$(git --no-pager tag | grep $new_tag || echo "")
            if [[ "$temp" = "$new_tag" ]]; then
                echo "delete remote tag $new_tag"
                git push origin --delete $new_tag
                git tag -d $new_tag
            fi
            git tag $new_tag
            echo "create tag $new_tag"
            git push origin $new_tag
            # commit=$(git --no-pager log --pretty=format:"%H" | grep -B 1 $commit | head -n 1)
            echo "after-$commit"
            msg=$(git --no-pager log --pretty=format:"- [%s](https://github.com/${{ github.repository}}/commit/%H)" $commit..HEAD)
            echo "$msg" > body.md
            echo "tag=$new_tag" >> $GITHUB_OUTPUT
            # 如果直接指向master，release会落后一个commit
            # gh release create -n "$msg" --target $new_tag $(date +%Y%m%d) ./app/*
        - name: Create Release
          uses: ncipollo/release-action@v1
          env:
            GH_TOKEN: ${{ github.token }}
          with:
            artifacts: "app/*"
            bodyFile: "body.md"
            tag: ${{ steps.ready.outputs.tag }}
