name: release

on:
  push:
    branches: ['master']
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.dockerignore'
  workflow_dispatch:
env:
  RUST_VERSION: 1.83.0
jobs:
  linux: 
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/inkroomtemp/rust_musl_build:1.83.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build
        run: |
          env
          rustup show
          mkdir out
          cargo build --release --target=x86_64-unknown-linux-musl
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-linux
          path: target/x86_64-unknown-linux-musl/release/m3u8-dl
  windows:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - name: Build
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
        run: |
          cargo build --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-windows
          path: target/release/m3u8-dl.exe
  mac: 
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - name: Build
        run: |
          cargo build --release && mv target/release/m3u8-dl target/release/m3u8-dl-mac
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-mac
          path: target/release/m3u8-dl-mac
  release:
    runs-on: ubuntu-20.04
    needs: ["mac","linux","windows"]
    permissions:
        contents: write
        packages: write
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-tags: true
            fetch-depth: 0
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            merge-multiple: true
            pattern: app-*
            path: app/
        - name: Release
          env:
            GH_TOKEN: ${{ github.token }}
          run: |
            new_tag=$(date +%Y%m%d)
            now_tag=$(curl -sSf https://api.github.com/repos/inkroom/m3u8-dl/releases/latest | jq --raw-output '.tag_name')
            if [[ "$new_tag" = "$now_tag" ]]
            then
              gh release delete $now_tag
              now_tag=$(curl -sSf https://api.github.com/repos/inkroom/m3u8-dl/releases | jq --raw-output '.[0].tag_name')
            fi
            commit=$(git rev-list -n 1 $now_tag)
            msg=$(git --no-pager log --pretty=format:"%s" $commit..HEAD | awk '{print "- " $0}')
            echo "$commit"
            gh release create -n "$msg" --target master $(date +%Y%m%d) ./app/*